# Generated by Django 3.0.6 on 2020-06-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studious', '0004_auto_20200621_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpaper',
            name='int_data_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpaper',
            name='int_data_share',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpaper',
            name='int_open_data',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
