# Generated by Django 3.0.6 on 2020-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studious', '0005_auto_20200622_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='index_by_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
